<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 31.05.16
 * Time: 15:03
 */

namespace App\DB;


class Buildings extends Parser
{

    protected $fillable = [
        'id',
        'title',
        'images',
        'levels',
        'woods',
        'stones',
        'foods',
        'ores',
        'times',
        'requirements',
        'hero_xp',
        'masters_hammers',
        'power',
        'bonuses'
    ];

    protected $casts = [
        'images' => 'array',
        'levels' => 'array',
        'woods'=> 'array' ,
        'stones'=> 'array',
        'foods'=> 'array',
        'ores'=> 'array',
        'times'=> 'array',
        'requirements'=> 'array',
        'hero_xp'=> 'array',
        'masters_hammers'=> 'array',
        'power'=> 'array',
        'bonuses'=> 'array',
    ];

    protected $guarded = [
        'created_at',
        'updated_at'
    ];

    public static function boot()
    {
        self::creating( function ($model) {
            if ( ! is_array($model->images)) {
                $model->images = [];
            }
            if ( ! is_array($model->levels)) {
                $model->levels = [];
            }
            if ( ! is_array($model->woods)) {
                $model->woods = [];
            }
            if ( ! is_array($model->stones)) {
                $model->stones = [];
            }
            if ( ! is_array($model->foods)) {
                $model->foods = [];
            }
            if ( ! is_array($model->ores)) {
                $model->ores = [];
            }
            if ( ! is_array($model->times)) {
                $model->times = [];
            }
            if ( ! is_array($model->requirements)) {
                $model->requirements = [];
            }
            if ( ! is_array($model->hero_xp)) {
                $model->hero_xp = [];
            }
            if ( ! is_array($model->masters_hammers)) {
                $model->masters_hammers = [];
            }
            if ( ! is_array($model->power)) {
                $model->power = [];
            }
            if ( ! is_array($model->bonuses)) {
                $model->bonuses = [];
            }
            
        });
        
        parent::boot(); // TODO: Change the autogenerated stub
    }


}