<?php

namespace App\DB;


class Materials extends Parser
{
    
    protected $fillable = [
        'id',
        'title',
        'images',
        'event',
        'used',
    ];

    protected $casts = [
        'images' => 'array',
        'used'=>'array',
    ];

    protected $guarded = [
        'created_at',
        'updated_at'
    ];

    public static function boot()
    {
        self::creating( function ($model) {
           if ( ! is_array($model->images)) {
               $model->images = [];
           }
            if ( ! is_array($model->used)) {
                $model->used = [];
            }
        });
        
        parent::boot(); // TODO: Change the autogenerated stub
    }

}